### ISSUE TITLE
Associating metadata (satellite values) with kmers

### ISSUE THREAD

**Issue by tbenavi1** [jermp/lphash#18]
Hello and thank you for this great tool! I was wondering if it would be possible to associate metadata with the kmers. The paper mentions abundance counts, reference identifiers, or contig identifiers as possible satellite values. How would one go about querying your lphash database for this information? Thanks for any insights.

(I understand that the database size and database construction time would not be optimized for this use case, but I am most interested in keeping a fast lookup time.)

**Comment by jermp** [comment]
Hi and thank you for your interest in LPHash.
This library provides you the hash function alone, it does not comprise further information. The paper explains that an application of locality-preserving hashing is to induce clusters of satellite values in a separate array that holds the values you want to associate to the kmers. Let V[1..n] be such array: V[i] stores the value of the kmer whose hash code is i. So, i is the hash code as returned by LPHash, for i = 1..n. You will see that V has clusters of very similar, if not identical, values.

Hope this explanation helps. Feel free to reach out if it does not!
Best,
-Giulio

**Comment by tbenavi1** [comment]
Thank you this makes sense.
