### ISSUE TITLE
Multithreading for query-p command

### ISSUE THREAD

**Issue by tbenavi1** [jermp/lphash#19]
Hello,

Would it be possible to implement multiple threads for the query-p command. In particular, a very simple implementation would just be to have each thread analyze a different subset of the sequences in the input fasta file. Thanks for any assistance.

**Comment by jermp** [comment]
Hi,
yes, we could use the excellent parsing library by Rob Patro, https://github.com/rob-p/FQFeeder.
See an example here https://github.com/jermp/fulgor/blob/main/tools/pseudoalign.cpp on how to use it.
I will probably add this to LPHash query command as well, as soon as possible!

Thanks and best,
-Giulio

**Comment by tbenavi1** [comment]
Thank you.
