### ISSUE TITLE
Different hashes error for S. cerevisiae

### ISSUE THREAD

**Issue by tbenavi1** [jermp/lphash#20]
Hello,

I ran lphash on the S. cerevisiae [reference genome](https://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000/146/045/GCA_000146045.2_R64/) and received the following error:

```
[Error] different hashes, maybe there were some Ns in the input (not supported as of now)
```

Specifically, I first ran bcalm with -kmer-size 31 and -abundance-min 1, then I ran ust with -k 31, then I ran lphash build-p with -k 31 and -m 15. As far as I can tell, there are no Ns in the genome.

Is this an error I should be concerned about? Thanks for your assistance. 

I do notice that the genome has upper and lower case letters. Does lphash convert everything to uppercase for both building and querying?

**Comment by tbenavi1** [comment]
I just confirmed that the output from ust does not have Ns. I also confirmed that the output from ust only has capital letters.

**Comment by jermp** [comment]
Hello,
I do not get the error you mention. Here is what I did.

`./bcalm -in GCA_000146045.2_R64_genomic.fna.gz -kmer-size 31 -abundance-min 1 -nb-cores 8`

`./ust -k 31 -i ~/bcalm/build/GCA_000146045.2_R64_genomic.fna.unitigs.fa`

`./lphash build-p -i ~/UST/GCA_000146045.2_R64.ust.k31.fa.gz -k 31 -m 15 -o test.lphash -d tmp --verbose --check`

`./lphash query-p -i test.lphash -q ~/UST/GCA_000146045.2_R64.ust.k31.fa.gz`

Are you sure you did something similar? What exactly are you querying?

**Comment by tbenavi1** [comment]
My apologies, the error was on my end. I had edited the code and that is what had caused the error. I'm sorry for wasting your time.

**Comment by jermp** [comment]
@tbenavi1 No worries at all! I'm glad to help. Should you need my assistance, do not hesitate to ask.
Cheers,
-Giulio
