### ISSUE TITLE
A kmer and its reverse complement hash to different values

### ISSUE THREAD

**Issue by tbenavi1** [jermp/lphash#22]
Hello,
Based on my testing, Lphash doesn't convert kmers into their canonical representation. I would expect a kmer and its reverse complement to hash to the same value.

For example, BCALM 2 converts all k-mers into their canonical representation with respect to reverse-complements.

I believe that the kmers will need to be converted to their canonical form both during the building and the querying steps. Thanks for any insight. 

Also, what is the expected output when you query lphash for a kmer that is not in the database? Does lphash return a particular value? I'm not 100% sure, but I think right now it will still output a hash number (that will collide with another kmer actually in the database). Thanks for any insights.

**Comment by jermp** [comment]
Hello @tbenavi1,
sorry for the late response but I was on vacation.

LPHash is a minimal perfect hash function for the given set of kmers, hence two different keys must have different hash codes. A kmer and its reverse complement are indeed two different strings (keys), thus they will have different hash codes assigned with very high probability.

I do not see any easy way of handling reverse complements.

Hope this helps. I also curious what you're trying to build given your interest in LPHash and SSHash.
Let me know if you'd like so that I can (hopefully) help you best.

Cheers,
-Giulio

**Comment by tbenavi1** [comment]
Thanks. Do you also know what happens if you query the database for a kmer that does not exist in the database?

Also, given that a kmer and its reverse complement hash to different values, I think that the process to make the input file for LPHash needs to be updated. Specifically, if the output of UST is X, and Y is the reverse complement of X (i.e, the reverse complements of all the sequences in X), then I think the input to LPHash needs to be X and Y concatenated together. The original output of UST will not contain all of the kmers in the initial sequence. Specifically, for every kmer in the initial sequence, either the kmer OR its reverse complement will be present exactly once in the UST output (since BCALM2 and UST treat canonical kmers as the same). However, when the user queries LPHash for that kmer they may not be aware that only the reverse complement was present in the UST output. 

Does this make sense? Is my reasoning/understanding correct? Thanks for any advice.

**Comment by jermp** [comment]
> Thanks. Do you also know what happens if you query the database for a kmer that does not exist in the database?

You're welcome. Yes, LPHash will still return an identifier -- there is no way for a MPHF to know if the queried key was actually indexed (this is an important requirement to achieve compact space).

Yes, what you're suggesting -- index both strands -- could be a solution. The space for LPHash would obviously double, though.

**Comment by tbenavi1** [comment]
I have been thinking about this a little more, and I think there is a fairly straightforward way to handle reverse complements in lphash (aka, both the forward and reverse complement kmers will hash to the same value). When calculating the minimizer of a given kmer, lphash could search both the forward and reverse complement m-mers. The minimizer would then be the one with the lowest hash, just as before. As for the position of the minimizer in the kmer, it would be calculated with respect to the kmer that is in the same direction as the minimizer. 

In the event of a tie for the minimizer the lexicographically smallest can be chosen. (I am not sure that leftmost would work anymore).

I don't believe there would have to be any other changes in the code, but I may be wrong.

Of course, this "canonical mode" could be a separate mode that is toggled by the user.

**Comment by jermp** [comment]
Thanks @tbenavi1, I'll think about this. At first sight it seems something similar I'm already doing in SSHash.

@yhhshb thought about this?

**Comment by yhhshb** [comment]
Hello @tbenavi1,

I think this might work, but the number of ambiguous minimizers will increase as well.
I have no idea how much the space for the fallback MPHF will increase though. 
It might be worth checking, given that the code for computing canonical minimizers is already there.
